#!/usr/bin/env python3
"""1.3 survival world — stand up the break-3 apparatus (R2 break 3: the world affords the acts).

R2's null had three structural breaks (docs/experiments/r2_drive_premise_check.md). Break 1
(the drive->corrective-action prior) and break 2 (measured-relief credit for interoceptive
world drives) shipped. Break 3 is the world layer: the void/superflat contingency world the
1.2 apparatus used does NOT afford the corrective acts (`eat` throws "no food in inventory",
`attack_nearest` throws "no hostile nearby"). This stands up a SURVIVAL world where the game's
own hunger mechanic drains (game-native pressure, D1: no synthetic sensor, no bespoke reward)
and food is present in the inventory, so `eat` is a single executable corrective act and the
break-1 prior -> break-2 credit loop can actually close.

This is a DIFFERENT apparatus from Exp 56: a survival `minecraft_player` world, NOT the frozen
`minecraft_bench` superflat contingency world (mobs off, floating slots). They share no world,
server, or body — so standing this up does not touch the Exp 56 EARNED result. It reuses
Exp 56's proven mechanics where they carry: the `fill.papermc.io/v3` download (the old
`api.papermc.io/v2` returns 410 Gone) and `exp56.common.RconControl` for the world script.

Version: Paper 1.20.4 (DECIDED 2026-09-13 — docs/plans/survival_world_1_3.md §"Minecraft
version"; the 1.3 platform, ported off the 1.16.5 the break-3 smoke first ran on). mineflayer
`^4.20.0` negotiates the protocol, so the bridge needs no version change. Design-relevant
mechanic delta vs 1.16.5: since 1.18, hostile mobs spawn only at block-light 0 (not <=7), which
sharpens the dark=danger contingency the Phase-1 classroom keys on. `scripts/exp56/` stays
1.16.5-pinned until its own re-baseline port.

Subcommands
-----------
``setup``    download Paper 1.20.4, write survival ``server.properties`` + ``eula.txt``
             (EULA acceptance needs the explicit ``--accept-eula`` flag — Mojang's agreement,
             not this script's to accept silently), print the start command.
``prepare``  against a RUNNING server WITH THE BRIDGE BOT JOINED: set time/gamerules and seed
             the bot's inventory with food over RCON. Idempotent. ``--induce-hunger`` applies a
             short game-native hunger effect to drive the loop quickly during WIRING tests (the
             real learning run lets hunger drain naturally).
``verify``   re-check difficulty/gamerules and that the bot holds food (exit 4 on mismatch).

Typical flow (Java 17+ — Paper 1.20.4 REQUIRES it; temurin@17 coexists with the temurin@11
the pinned exp56 server still needs):

    brew install --cask temurin@17
    python scripts/survival_world/setup_world.py setup --dir ~/maxim-mc-survival \\
        --accept-eula --rcon-password '<pw>'
    (cd ~/maxim-mc-survival && java -jar paper-1.20.4.jar nogui)     # first boot
    # in another terminal, connect the bridge so the bot 'maxim' joins:
    (cd scripts/minecraft_bridge && node index.js --mc_host=127.0.0.1 --mc_port=25565 \\
        --bridge_port=25567 --username=maxim)
    python scripts/survival_world/setup_world.py prepare --rcon-password '<pw>' --username maxim
    python scripts/survival_world/setup_world.py verify  --rcon-password '<pw>' --username maxim
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SCRIPTS_DIR))

from exp56.common import RconControl  # noqa: E402  (proven RCON client — shared dev tooling)

MC_VERSION = "1.20.4"
# PaperMC's Fill v3 API (the old api.papermc.io v2 returns 410 Gone — exp56 lesson).
PAPER_API = f"https://fill.papermc.io/v3/projects/paper/versions/{MC_VERSION}/builds/latest"

# level-type=minecraft\:normal (a normal world — terrain, animals, food; 1.19+ takes the
# NAMESPACED id, the pre-1.19 bare `DEFAULT` is not a valid modern value) so
# `eat`/`attack_nearest` have something to act on; a fixed seed so the world is reproducible.
# difficulty=normal (NOT peaceful) so the game's hunger mechanic drains and mobs afford the
# threat channel. NOTE the literal `\:` — server.properties is a Java .properties file, where
# an unescaped `:` in a VALUE is tolerated by most parsers but the escaped form is canonical;
# Paper writes it back escaped, so writing it escaped keeps setup idempotent under diff.
SERVER_PROPERTIES = """\
# 1.3 survival world (generated by scripts/survival_world/setup_world.py). R2 break 3:
# a survival world whose native hunger mechanic drains (game-native pressure) and whose
# inventory can hold food, so the corrective `eat` act is executable.
online-mode=false
enable-rcon=true
rcon.port={rcon_port}
rcon.password={rcon_password}
level-type=minecraft\\:normal
level-seed=maxim-oasis-1
level-name=survival_world
gamemode=survival
difficulty=normal
spawn-monsters=true
spawn-animals=true
allow-nether=false
spawn-protection=0
view-distance=8
max-players=4
motd=Maxim Oasis survival world (R2 break 3)
enable-command-block=false
"""


def _setup(args: argparse.Namespace) -> int:
    server_dir = Path(args.dir).expanduser()
    server_dir.mkdir(parents=True, exist_ok=True)
    if not args.accept_eula:
        print(
            "Refusing to write eula.txt without --accept-eula: accepting Mojang's EULA\n"
            "(https://aka.ms/MinecraftEULA) is the operator's action, not this script's."
        )
        return 2
    jar = server_dir / f"paper-{MC_VERSION}.jar"
    if not jar.exists():
        try:
            from maxim.utils.http import download_to_file, fetch_url

            build = json.loads(fetch_url(PAPER_API, timeout=30).content)
            dl = build["downloads"]["server:default"]
            print(f"downloading Paper {MC_VERSION} build {build['id']} ({dl['size']} bytes) …")
            download_to_file(dl["url"], jar, expected_bytes=int(dl["size"]))
            print(f"downloaded + size-verified: {jar}")
        except Exception as exc:
            # download_to_file writes straight to the final path with no .partial staging,
            # so a mid-stream drop / size mismatch leaves a truncated jar that the NEXT run's
            # `if not jar.exists()` would treat as complete. Remove it so the next run re-downloads.
            jar.unlink(missing_ok=True)
            print(
                f"WARNING: automatic Paper download failed ({type(exc).__name__}: {exc}).\n"
                f"Download Paper {MC_VERSION} manually from https://papermc.io/downloads/all "
                f"and save it as {jar}"
            )
            return 1
    (server_dir / "eula.txt").write_text("eula=true\n")
    (server_dir / "server.properties").write_text(
        SERVER_PROPERTIES.format(rcon_port=args.rcon_port, rcon_password=args.rcon_password)
    )
    print(
        f"\nsetup complete in {server_dir}\n"
        f"  Java 17+ required (Paper {MC_VERSION}; `brew install --cask temurin@17`).\n"
        f"  first boot:  (cd {server_dir} && java -jar paper-{MC_VERSION}.jar nogui)\n"
        f"  then connect the bridge (bot joins as the username you pass to prepare), then:\n"
        f"  python scripts/survival_world/setup_world.py prepare "
        f"--rcon-port {args.rcon_port} --rcon-password '<pw>' --username maxim"
    )
    return 0


# Idempotent world conditions. doImmediateRespawn so a death does not park the AUT on a
# respawn screen; keepInventory so a death does not silently strip the seeded food (which
# would masquerade as "eat unavailable"); time frozen at day for reproducible conditions.
_GAMERULES = {
    "doImmediateRespawn": "true",
    "keepInventory": "true",
    "doDaylightCycle": "false",
}


def _prepare(args: argparse.Namespace) -> int:
    rcon = RconControl(args.rcon_host, args.rcon_port, args.rcon_password)
    try:
        print(f"rcon> difficulty normal\n      {rcon.command('difficulty normal').strip() or '(ok)'}")
        print(f"rcon> time set day\n      {rcon.command('time set day').strip() or '(ok)'}")
        for rule, val in _GAMERULES.items():
            resp = rcon.command(f"gamerule {rule} {val}").strip()
            print(f"rcon> gamerule {rule} {val}\n      {resp or '(ok)'}")
        # Seed food so `eat` is a single executable corrective act. Bread is a stable,
        # non-perishable food the bridge's `eat` handler already matches by name.
        give = f"give {args.username} minecraft:bread 64"
        resp = rcon.command(give).strip()
        print(f"rcon> {give}\n      {resp or '(ok)'}")
        if "no player" in resp.lower() or "was found" in resp.lower():
            print(
                f"\nWARNING: no player named {args.username!r} online — start the bridge first "
                f"(node index.js --username={args.username}) so the bot joins, then re-run prepare."
            )
            return 4
        if args.induce_hunger:
            # A game-native hunger effect to drive the loop quickly during WIRING tests only.
            # The real learning run lets hunger drain from ordinary activity (D1).
            hun = f"effect give {args.username} minecraft:hunger 40 4"
            print(f"rcon> {hun}\n      {rcon.command(hun).strip() or '(ok)'}")
        print("\nprepare complete — the bot holds food and hunger will drain (game-native).")
        return 0
    finally:
        rcon.close()


def _verify(args: argparse.Namespace) -> int:
    rcon = RconControl(args.rcon_host, args.rcon_port, args.rcon_password)
    bad = 0
    try:
        for rule, val in _GAMERULES.items():
            resp = rcon.command(f"gamerule {rule}").strip()
            ok = val in resp
            print(f"gamerule {rule}: {resp}  {'OK' if ok else 'MISMATCH (want ' + val + ')'}")
            bad += 0 if ok else 1
        # `clear <player> bread 0` reports the count without removing (vanilla dry-run form).
        # Replies "Found N matching item(s) on player X" (has food) or "No items were found
        # on player X" (none) — the commands.clear.testing.* translation keys, unchanged
        # 1.16→1.20.4 (re-confirm on the first 1.20.4 boot) — match the FAILURE string, not a
        # "0 item" substring that never appears in either reply (which would make this guard
        # vacuous).
        cnt = rcon.command(f"clear {args.username} minecraft:bread 0").strip()
        low = cnt.lower()
        holds = "no items were found" not in low and "no player" not in low
        print(f"food held by {args.username}: {cnt}  {'OK' if holds else 'NONE — re-run prepare'}")
        bad += 0 if holds else 1
    finally:
        rcon.close()
    if bad:
        print(f"\nVERIFY FAILED ({bad} mismatch) — the world does not yet afford the corrective act.")
        return 4
    print("\nverify OK — the survival world affords `eat`; break-3 loop can close.")
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="1.3 survival world (R2 break 3) setup")
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("setup", help="download Paper + write survival configs (needs --accept-eula)")
    s.add_argument("--dir", default="~/maxim-mc-survival")
    s.add_argument("--accept-eula", action="store_true")
    s.add_argument("--rcon-port", type=int, default=25575)
    s.add_argument("--rcon-password", required=True)
    s.set_defaults(fn=_setup)

    for name, fn, helptext in (
        ("prepare", _prepare, "seed food + set conditions over RCON (bot must be joined)"),
        ("verify", _verify, "re-check conditions + food (exit 4 on mismatch)"),
    ):
        q = sub.add_parser(name, help=helptext)
        q.add_argument("--rcon-host", default="127.0.0.1")
        q.add_argument("--rcon-port", type=int, default=25575)
        q.add_argument("--rcon-password", required=True)
        q.add_argument("--username", default="maxim", help="the bridge bot's username")
        if name == "prepare":
            q.add_argument(
                "--induce-hunger",
                action="store_true",
                help="apply a short game-native hunger effect for wiring tests (not the real run)",
            )
        q.set_defaults(fn=fn)

    args = p.parse_args(argv)
    return int(args.fn(args))


if __name__ == "__main__":
    raise SystemExit(main())
