#!/usr/bin/env python3
"""Exp 56 world setup — stand up the frozen live apparatus in a few commands.

The pre-registration's live apparatus (exp56_four_arm_sharing_preregistration.md
§Apparatus, the L11-capture lineage): a Paper offline-mode server on a
superflat world with the surface at y=63 (feet at y=64 — the bench body's
`y_altitude` neutral and the frozen rest anchor), daylight/weather/mob-spawning
off, RCON enabled, and the four frozen contingency slots built as floating
stone enclosures at their frozen far+high coordinates (amendment 2: the
situation signature is distance_from_spawn + y_altitude — light_level was
dropped after the live bridge measured it dead). Everything here is
OPERATIONAL tooling —
nothing touches the frozen science constants, which live in
``scripts/exp56/common.py::FROZEN`` and are read from there, never re-typed.

**Re-baseline port (2026-09-18, roadmap_1_3.md Phase 0 + survival_world_1_3.md §Minecraft version):**
the EARNED campaign ran on Paper 1.16.5 (campaign hash ``9905d4d8``). The 1.3 platform is Paper 1.20.4, and the Exp 56 ledger
row's re-run triggers ("Minecraft bridge protocol change", the minor-version heartbeat) have fired,
so this builder now targets 1.20.4 like ``scripts/survival_world/setup_world.py``: same superflat
surface (y=63, feet y=64 — the frozen neutral), same gamerules, same slot enclosures; only the
server version, the 1.19+ ``level-type`` spelling, the layer count (the 1.18+ world floor is y=-64,
so the stack grows to 128 layers to keep the surface at y=63 — MEASURED by ``verify``'s surface probe)
and the Java requirement change. The RCON apparatus (``prepare``) is version-agnostic; the campaign
rows now carry the server's own ``version`` reply (``server_version``) so the platform is measured,
not asserted, and the analyzer refuses a file that mixes platforms. A world folder generated by another version
refuses ``setup`` (the survival builder's stamp guard) — use a FRESH ``--dir`` for the re-baseline;
the 1.16.5 world stays where it was, untouched.

Subcommands
-----------
``setup``    download Paper 1.20.4, write ``server.properties`` + ``eula.txt``
             (EULA acceptance requires the explicit ``--accept-eula`` flag —
             it is Mojang's agreement, not this script's to accept silently),
             and print the start command.
``prepare``  against a RUNNING server: set the gamerules/time/spawn and build
             the slot enclosures + rest pad over RCON. Idempotent.
``verify``   re-check the gamerules and slot structures over RCON (exit 4 on
             any mismatch — the S3 refusal convention).

Typical flow (see scripts/exp56/README.md for the full runbook):

    python scripts/exp56/setup_world.py setup --dir ~/exp56_server_1204 --accept-eula \
        --rcon-password '<pw>'
    (cd ~/exp56_server_1204 && java -jar paper-1.20.4.jar nogui)   # first boot (Java 17+)
    python scripts/exp56/setup_world.py prepare --rcon-password '<pw>'
    python scripts/exp56/setup_world.py verify  --rcon-password '<pw>'
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SCRIPTS_DIR))

from _paper_server import (  # noqa: E402
    download_paper,
    java_major,
    java_start_command,
    java_version_line,
    refuse_stale_world,
    write_world_stamp,
)
from exp56 import common as C  # noqa: E402

MC_VERSION = "1.20.4"
# PaperMC's Fill v3 API (the old api.papermc.io v2 returns 410 Gone).
PAPER_API = f"https://fill.papermc.io/v3/projects/paper/versions/{MC_VERSION}/builds/latest"

SERVER_PROPERTIES = """\
# Exp 56 frozen live apparatus (generated by scripts/exp56/setup_world.py).
# The prereg's world requirements: offline mode, superflat surface at y=63
# (feet y=64 = the bench body's y_altitude neutral), RCON for the world
# script, spawn protection off (RCON builds the slot enclosures).
online-mode=false
enable-rcon=true
rcon.port={rcon_port}
rcon.password={rcon_password}
level-type=minecraft\\:flat
# 1.16+ takes JSON generator settings (the legacy layer-string crashes boot
# with a MalformedJsonException — found by booting, not by reading); 1.19+ spells the
# level type minecraft:flat with the colon escaped for the properties parser (the survival
# builder's spelling) and takes the SAME layers JSON.
# SINCE 1.18 the flat generator stacks layers from the dimension floor y=-64 (which is why the
# default superflat surface moved to y=-60), so the 1.16.5 stack (1+62+1 = 64 layers) would put
# the surface at y=-1 with every `prepare` check still green. 1+126+1 = 128 layers = -64..63:
# bedrock at -64, grass at y=63, feet y=64 — the FROZEN neutral, unchanged. `verify` MEASURES
# it with a surface probe off anything `prepare` placed (1.20.4 silently falls back to the
# default flat preset on a schema-mismatched JSON where 1.16 crashed).
generator-settings={{"layers":[{{"block":"minecraft:bedrock","height":1}},{{"block":"minecraft:dirt","height":126}},{{"block":"minecraft:grass_block","height":1}}],"biome":"minecraft:plains"}}
level-name=exp56_world
spawn-protection=0
view-distance=8
max-players=4
motd=Exp 56 four-arm benchmark world (frozen apparatus; re-baseline on Paper {mc_version})
enable-command-block=false
spawn-monsters=false
"""


def cmd_setup(args: argparse.Namespace) -> int:
    server_dir = Path(args.dir).expanduser().resolve()
    server_dir.mkdir(parents=True, exist_ok=True)

    jv = java_version_line()
    major = java_major(jv)
    if jv is None:
        print(
            f"WARNING: no `java` on PATH. Paper {MC_VERSION} REQUIRES Java 17+ (macOS: brew install --cask temurin@17)."
        )
    else:
        print(f"java on PATH: {jv}")
        if major is None or major < 17:
            print(
                f"WARNING: that is not Java 17+ — Paper {MC_VERSION} refuses it; the start command below pins Java 17 per invocation."
            )

    # The stale-world guard (shared with the survival builder): the 1.16.5 world is the EARNED
    # apparatus and stays put — the re-baseline uses a FRESH --dir.
    refusal = refuse_stale_world(server_dir, "exp56_world", MC_VERSION, force=args.force_world)
    if refusal:
        print(refusal)
        return 2

    if not args.accept_eula:
        print(
            "\nREFUSING to write eula.txt: accepting Mojang's EULA "
            "(https://aka.ms/MinecraftEULA) is the operator's action, not this script's.\n"
            "Re-run with --accept-eula once you have read and accept it."
        )
        return 2

    jar = server_dir / f"paper-{MC_VERSION}.jar"
    if not download_paper(MC_VERSION, jar):
        return 1  # no jar, no stamp: the next run re-downloads instead of booting a truncated jar

    (server_dir / "eula.txt").write_text("eula=true\n")
    (server_dir / "server.properties").write_text(
        SERVER_PROPERTIES.format(rcon_port=args.rcon_port, rcon_password=args.rcon_password, mc_version=MC_VERSION)
    )
    write_world_stamp(server_dir, MC_VERSION, stamped_by="scripts/exp56/setup_world.py")
    print(
        "\nsetup done. FIRST BOOT (generates the world; needs network for Paperclip's first patch;"
        " leave it running for `prepare`):\n"
        f"  {java_start_command(server_dir, jar.name)}\n"
        "then, from the repo root:\n"
        f"  python scripts/exp56/setup_world.py prepare --rcon-port {args.rcon_port} --rcon-password '<pw>'\n"
        f"  python scripts/exp56/setup_world.py verify  --rcon-port {args.rcon_port} --rcon-password '<pw>'"
        "   # the surface probe MEASURES y=63"
    )
    return 0


def _slot_boxes() -> list[tuple[dict, str]]:
    """The frozen slots as (anchor, fill-command) pairs — a hollow stone box
    per slot: floor at y-1, roof at y+3, interior 3x3x3 air (dark; the bot
    is teleported inside; all roster actions are turns, so no pathing out).
    Coordinates come from the FROZEN constants, never re-typed here."""
    out = []
    for slot in C.FROZEN["contingency_slots"]:
        x, y, z = int(slot["x"]), int(slot["y"]), int(slot["z"])
        cmd = f"fill {x - 2} {y - 1} {z - 2} {x + 2} {y + 3} {z + 2} minecraft:stone hollow"
        out.append((slot, cmd))
    return out


PREPARE_COMMANDS = (
    "gamerule doDaylightCycle false",
    "gamerule doWeatherCycle false",
    "gamerule doMobSpawning false",
    "gamerule doImmediateRespawn true",
    "difficulty peaceful",
    "time set noon",
    "weather clear",
)


def _rcon(args: argparse.Namespace) -> "C.RconControl":
    return C.RconControl(args.rcon_host, args.rcon_port, args.rcon_password)


def cmd_prepare(args: argparse.Namespace) -> int:
    rest = C.FROZEN["rest_anchor"]
    rcon = _rcon(args)
    try:
        for cmd in PREPARE_COMMANDS:
            print(f"rcon> {cmd}\n      {rcon.command(cmd).strip() or '(ok)'}")
        # World spawn = the rest anchor, set BEFORE the bridge bot ever
        # joins: the bridge's distance_from_spawn reads the bot's spawn
        # point, which is captured at join.
        cmd = f"setworldspawn {int(rest['x'])} {int(rest['y'])} {int(rest['z'])}"
        print(f"rcon> {cmd}\n      {rcon.command(cmd).strip() or '(ok)'}")
        # Force-load every anchor's chunks PERMANENTLY: fills fail with
        # "That position is not loaded" otherwise (found by executing), and
        # the campaign's teleports must never land in an unloading chunk.
        anchors = [rest] + list(C.FROZEN["contingency_slots"])
        for a in anchors:
            fl = f"forceload add {int(a['x']) - 2} {int(a['z']) - 2} {int(a['x']) + 2} {int(a['z']) + 2}"
            print(f"rcon> {fl}\n      {rcon.command(fl).strip() or '(ok)'}")
        # A clear stone pad at the rest anchor so feet land at exactly y=64
        # (the y_altitude neutral).
        pad = f"fill {int(rest['x']) - 2} {int(rest['y']) - 1} {int(rest['z']) - 2} {int(rest['x']) + 2} {int(rest['y']) - 1} {int(rest['z']) + 2} minecraft:stone"
        print(f"rcon> {pad}\n      {rcon.command(pad).strip() or '(ok)'}")
        for slot, cmd in _slot_boxes():
            print(f"rcon> {cmd}   # slot {slot}\n      {rcon.command(cmd).strip() or '(ok)'}")
    finally:
        rcon.close()
    print("\nprepare done. Run `verify` next, then start the bridge (see scripts/exp56/README.md).")
    return 0


def cmd_verify(args: argparse.Namespace) -> int:
    failures: list[str] = []
    rcon = _rcon(args)
    try:
        for rule, want in (("doDaylightCycle", "false"), ("doWeatherCycle", "false"), ("doMobSpawning", "false")):
            resp = rcon.command(f"gamerule {rule}")
            if want not in resp.lower():
                failures.append(f"gamerule {rule}: {resp.strip()!r} (want {want})")
        for slot, _cmd in _slot_boxes():
            x, y, z = int(slot["x"]), int(slot["y"]), int(slot["z"])
            resp = rcon.command(f"execute if block {x} {y - 1} {z} minecraft:stone run seed")
            if "seed" not in resp.lower():
                failures.append(f"slot {slot}: floor at ({x},{y - 1},{z}) is not stone — run `prepare`")
        rest = C.FROZEN["rest_anchor"]
        resp = rcon.command(
            f"execute if block {int(rest['x'])} {int(rest['y']) - 1} {int(rest['z'])} minecraft:stone run seed"
        )
        if "seed" not in resp.lower():
            failures.append("rest anchor pad is not stone — run `prepare`")
        # Surface probe OUTSIDE anything `prepare` placed (off the pad's ±2 footprint, same
        # force-loaded chunk): since 1.18 the flat generator stacks layers from y=-64, so a
        # mis-sized stack (or 1.20.4's silent fallback to the default preset) puts the ground
        # plane elsewhere while the pad floats and every check above stays green. Measured.
        px, pz = int(rest["x"]) + 8, int(rest["z"]) + 8
        for probe, want in (
            (f"execute if block {px} 63 {pz} minecraft:grass_block run seed", "grass_block at y=63"),
            (f"execute if block {px} 64 {pz} minecraft:air run seed", "air at y=64"),
        ):
            if "seed" not in rcon.command(probe).lower():
                failures.append(
                    f"surface probe at ({px},{pz}): expected {want} — the flat layers do not put the "
                    f"surface at y=63 on this server (server.properties generator-settings; see the comment there)"
                )
    finally:
        rcon.close()
    if failures:
        print("verify: FAIL")
        for f in failures:
            print(f"  - {f}")
        return 4
    print("verify: OK — gamerules set, rest pad + all 4 slot enclosures in place, surface measured at y=63.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("setup", help="download Paper + write configs (needs --accept-eula)")
    p.add_argument("--dir", required=True, help="server directory (created if absent)")
    p.add_argument(
        "--force-world",
        action="store_true",
        help="accept an in-place world upgrade of an existing world folder (default: refuse — use a fresh --dir; the 1.16.5 world is the EARNED apparatus)",
    )
    p.add_argument("--accept-eula", action="store_true", help="you have read and accept Mojang's EULA")
    p.add_argument("--rcon-port", type=int, default=25575)
    p.add_argument("--rcon-password", required=True)
    p.set_defaults(func=cmd_setup)

    for name, fn, help_ in (
        ("prepare", cmd_prepare, "set gamerules + build the frozen slots (server must be running)"),
        ("verify", cmd_verify, "re-check gamerules + slot structures (exit 4 on mismatch)"),
    ):
        p = sub.add_parser(name, help=help_)
        p.add_argument("--rcon-host", default="127.0.0.1")
        p.add_argument("--rcon-port", type=int, default=25575)
        p.add_argument("--rcon-password", required=True)
        p.set_defaults(func=fn)

    args = ap.parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
