#!/usr/bin/env python3
"""Exp 56 world setup — stand up the frozen live apparatus in a few commands.

The pre-registration's live apparatus (exp56_four_arm_sharing_preregistration.md
§Apparatus, the L11-capture lineage): a Paper 1.16.5 offline-mode server on a
superflat world with the surface at y=63 (feet at y=64 — the bench body's
`y_altitude` neutral and the frozen rest anchor), daylight/weather/mob-spawning
off, RCON enabled, and the four frozen contingency slots built as floating
stone enclosures at their frozen far+high coordinates (amendment 2: the
situation signature is distance_from_spawn + y_altitude — light_level was
dropped after the live bridge measured it dead). Everything here is
OPERATIONAL tooling —
nothing touches the frozen science constants, which live in
``scripts/exp56/common.py::FROZEN`` and are read from there, never re-typed.

Subcommands
-----------
``setup``    download Paper 1.16.5, write ``server.properties`` + ``eula.txt``
             (EULA acceptance requires the explicit ``--accept-eula`` flag —
             it is Mojang's agreement, not this script's to accept silently),
             and print the start command.
``prepare``  against a RUNNING server: set the gamerules/time/spawn and build
             the slot enclosures + rest pad over RCON. Idempotent.
``verify``   re-check the gamerules and slot structures over RCON (exit 4 on
             any mismatch — the S3 refusal convention).

Typical flow (see scripts/exp56/README.md for the full runbook):

    python scripts/exp56/setup_world.py setup --dir ~/exp56_server --accept-eula \
        --rcon-password '<pw>'
    (cd ~/exp56_server && java -jar paper-1.16.5.jar nogui)   # first boot
    python scripts/exp56/setup_world.py prepare --rcon-password '<pw>'
    python scripts/exp56/setup_world.py verify  --rcon-password '<pw>'
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SCRIPTS_DIR))

from exp56 import common as C  # noqa: E402

MC_VERSION = "1.16.5"
# PaperMC's Fill v3 API (the old api.papermc.io v2 returns 410 Gone).
PAPER_API = f"https://fill.papermc.io/v3/projects/paper/versions/{MC_VERSION}/builds/latest"

SERVER_PROPERTIES = """\
# Exp 56 frozen live apparatus (generated by scripts/exp56/setup_world.py).
# The prereg's world requirements: offline mode, superflat surface at y=63
# (feet y=64 = the bench body's y_altitude neutral), RCON for the world
# script, spawn protection off (RCON builds the slot enclosures).
online-mode=false
enable-rcon=true
rcon.port={rcon_port}
rcon.password={rcon_password}
level-type=FLAT
# 1.16+ takes JSON generator settings (the legacy layer-string crashes boot
# with a MalformedJsonException — found by booting, not by reading):
# bedrock + 62 dirt + grass = surface y=63, feet y=64 (the frozen neutral).
generator-settings={{"layers":[{{"block":"minecraft:bedrock","height":1}},{{"block":"minecraft:dirt","height":62}},{{"block":"minecraft:grass_block","height":1}}],"biome":"minecraft:plains"}}
level-name=exp56_world
spawn-protection=0
view-distance=8
max-players=4
motd=Exp 56 four-arm benchmark world (frozen apparatus)
enable-command-block=false
spawn-monsters=false
"""


def _java_version() -> str | None:
    java = shutil.which("java")
    if not java:
        return None
    out = subprocess.run([java, "-version"], capture_output=True, text=True)
    return (out.stderr or out.stdout).splitlines()[0] if (out.stderr or out.stdout) else "unknown"


def cmd_setup(args: argparse.Namespace) -> int:
    server_dir = Path(args.dir).expanduser().resolve()
    server_dir.mkdir(parents=True, exist_ok=True)

    jv = _java_version()
    if jv is None:
        print("WARNING: no `java` on PATH. Minecraft 1.16.5 needs Java 11-16 (NOT 17+):")
        print("  macOS: brew install openjdk@11   (then use its bin/java to start the server)")
    else:
        print(f"java: {jv}")
        if any(f'"{v}' in jv for v in ("17", "18", "19", "2")):
            print(
                "WARNING: this looks newer than Java 16 — Minecraft 1.16.5 generally refuses "
                "Java 17+. Install openjdk@11 and start the server with that java."
            )

    if not args.accept_eula:
        print(
            "\nREFUSING to write eula.txt: accepting Mojang's EULA "
            "(https://aka.ms/MinecraftEULA) is the operator's action, not this script's.\n"
            "Re-run with --accept-eula once you have read and accept it."
        )
        return 2
    (server_dir / "eula.txt").write_text("eula=true\n")

    (server_dir / "server.properties").write_text(
        SERVER_PROPERTIES.format(rcon_port=args.rcon_port, rcon_password=args.rcon_password)
    )

    jar = server_dir / f"paper-{MC_VERSION}.jar"
    if jar.is_file():
        print(f"paper jar already present: {jar}")
    else:
        try:
            import hashlib

            from maxim.utils.http import download_to_file, fetch_url

            build = json.loads(fetch_url(PAPER_API, timeout=30).content)
            dl = build["downloads"]["server:default"]
            print(f"downloading Paper {MC_VERSION} build {build['id']} ({dl['size']} bytes) …")
            download_to_file(dl["url"], jar, expected_bytes=int(dl["size"]))
            digest = hashlib.sha256(jar.read_bytes()).hexdigest()
            want = dl["checksums"]["sha256"]
            if digest != want:
                jar.unlink()
                raise RuntimeError(f"sha256 mismatch: got {digest}, want {want}")
            print(f"downloaded + sha256-verified: {jar}")
        except Exception as exc:
            print(
                f"WARNING: automatic Paper download failed ({type(exc).__name__}: {exc}).\n"
                f"Download Paper {MC_VERSION} manually from https://papermc.io/downloads/all "
                f"and place it at {jar}"
            )

    print(
        "\nsetup done. FIRST BOOT (generates the world; leave it running for `prepare`):\n"
        f"  cd {server_dir} && java -Xms1G -Xmx2G -jar {jar.name} nogui\n"
        "then, from the repo root:\n"
        f"  python scripts/exp56/setup_world.py prepare --rcon-port {args.rcon_port} --rcon-password '<pw>'"
    )
    return 0


def _slot_boxes() -> list[tuple[dict, str]]:
    """The frozen slots as (anchor, fill-command) pairs — a hollow stone box
    per slot: floor at y-1, roof at y+3, interior 3x3x3 air (dark; the bot
    is teleported inside; all roster actions are turns, so no pathing out).
    Coordinates come from the FROZEN constants, never re-typed here."""
    out = []
    for slot in C.FROZEN["contingency_slots"]:
        x, y, z = int(slot["x"]), int(slot["y"]), int(slot["z"])
        cmd = f"fill {x - 2} {y - 1} {z - 2} {x + 2} {y + 3} {z + 2} minecraft:stone hollow"
        out.append((slot, cmd))
    return out


PREPARE_COMMANDS = (
    "gamerule doDaylightCycle false",
    "gamerule doWeatherCycle false",
    "gamerule doMobSpawning false",
    "gamerule doImmediateRespawn true",
    "difficulty peaceful",
    "time set noon",
    "weather clear",
)


def _rcon(args: argparse.Namespace) -> "C.RconControl":
    return C.RconControl(args.rcon_host, args.rcon_port, args.rcon_password)


def cmd_prepare(args: argparse.Namespace) -> int:
    rest = C.FROZEN["rest_anchor"]
    rcon = _rcon(args)
    try:
        for cmd in PREPARE_COMMANDS:
            print(f"rcon> {cmd}\n      {rcon.command(cmd).strip() or '(ok)'}")
        # World spawn = the rest anchor, set BEFORE the bridge bot ever
        # joins: the bridge's distance_from_spawn reads the bot's spawn
        # point, which is captured at join.
        cmd = f"setworldspawn {int(rest['x'])} {int(rest['y'])} {int(rest['z'])}"
        print(f"rcon> {cmd}\n      {rcon.command(cmd).strip() or '(ok)'}")
        # Force-load every anchor's chunks PERMANENTLY: fills fail with
        # "That position is not loaded" otherwise (found by executing), and
        # the campaign's teleports must never land in an unloading chunk.
        anchors = [rest] + list(C.FROZEN["contingency_slots"])
        for a in anchors:
            fl = f"forceload add {int(a['x']) - 2} {int(a['z']) - 2} {int(a['x']) + 2} {int(a['z']) + 2}"
            print(f"rcon> {fl}\n      {rcon.command(fl).strip() or '(ok)'}")
        # A clear stone pad at the rest anchor so feet land at exactly y=64
        # (the y_altitude neutral).
        pad = f"fill {int(rest['x']) - 2} {int(rest['y']) - 1} {int(rest['z']) - 2} {int(rest['x']) + 2} {int(rest['y']) - 1} {int(rest['z']) + 2} minecraft:stone"
        print(f"rcon> {pad}\n      {rcon.command(pad).strip() or '(ok)'}")
        for slot, cmd in _slot_boxes():
            print(f"rcon> {cmd}   # slot {slot}\n      {rcon.command(cmd).strip() or '(ok)'}")
    finally:
        rcon.close()
    print("\nprepare done. Run `verify` next, then start the bridge (see scripts/exp56/README.md).")
    return 0


def cmd_verify(args: argparse.Namespace) -> int:
    failures: list[str] = []
    rcon = _rcon(args)
    try:
        for rule, want in (("doDaylightCycle", "false"), ("doWeatherCycle", "false"), ("doMobSpawning", "false")):
            resp = rcon.command(f"gamerule {rule}")
            if want not in resp.lower():
                failures.append(f"gamerule {rule}: {resp.strip()!r} (want {want})")
        for slot, _cmd in _slot_boxes():
            x, y, z = int(slot["x"]), int(slot["y"]), int(slot["z"])
            resp = rcon.command(f"execute if block {x} {y - 1} {z} minecraft:stone run seed")
            if "seed" not in resp.lower():
                failures.append(f"slot {slot}: floor at ({x},{y - 1},{z}) is not stone — run `prepare`")
        rest = C.FROZEN["rest_anchor"]
        resp = rcon.command(
            f"execute if block {int(rest['x'])} {int(rest['y']) - 1} {int(rest['z'])} minecraft:stone run seed"
        )
        if "seed" not in resp.lower():
            failures.append("rest anchor pad is not stone — run `prepare`")
    finally:
        rcon.close()
    if failures:
        print("verify: FAIL")
        for f in failures:
            print(f"  - {f}")
        return 4
    print("verify: OK — gamerules set, rest pad + all 4 slot enclosures in place.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("setup", help="download Paper + write configs (needs --accept-eula)")
    p.add_argument("--dir", required=True, help="server directory (created if absent)")
    p.add_argument("--accept-eula", action="store_true", help="you have read and accept Mojang's EULA")
    p.add_argument("--rcon-port", type=int, default=25575)
    p.add_argument("--rcon-password", required=True)
    p.set_defaults(func=cmd_setup)

    for name, fn, help_ in (
        ("prepare", cmd_prepare, "set gamerules + build the frozen slots (server must be running)"),
        ("verify", cmd_verify, "re-check gamerules + slot structures (exit 4 on mismatch)"),
    ):
        p = sub.add_parser(name, help=help_)
        p.add_argument("--rcon-host", default="127.0.0.1")
        p.add_argument("--rcon-port", type=int, default=25575)
        p.add_argument("--rcon-password", required=True)
        p.set_defaults(func=fn)

    args = ap.parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
